"""
Build a PR body markdown file from gate.json and the execution report.

Usage:
  python scripts/build_pr_body.py \
    --story-id PROT-101 \
    --gate /tmp/gate.json \
    --report-dir traceability/reports/ \
    --out /tmp/pr_body.md

Optional env var:
  JIRA_DATA_URL  Used to build a clickable link to the ticket source.
"""
import argparse
import json
import os
from pathlib import Path


def main():
    """
    Build a markdown PR body from gate.json and the execution report.

    When the report JSON is absent the counts silently default to 0/0 (no error raised).
    The output file is always overwritten. JIRA_DATA_URL being absent produces a plain
    story-ID reference instead of a hyperlink.
    """
    parser = argparse.ArgumentParser()
    parser.add_argument("--story-id", required=True)
    parser.add_argument("--gate", required=True)
    parser.add_argument("--report-dir", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    gate = json.loads(Path(args.gate).read_text())
    report_path = Path(args.report_dir) / f"{args.story_id}_report.json"
    report = json.loads(report_path.read_text()) if report_path.exists() else {}

    status = gate.get("status", "red")
    reason = gate.get("reason", "")
    badge = "✅ GREEN" if status == "green" else "❌ RED"

    passed = report.get("passed", 0)
    failed = report.get("failed", 0)
    output = report.get("output", "")
    commit_sha = (report.get("commit_sha", "") or "")[:7]
    timestamp = (report.get("timestamp", "") or "")[:19].replace("T", " ")

    jira_base = os.environ.get("JIRA_DATA_URL", "").rstrip("/")
    ticket_ref = (
        f"[{args.story_id}]({jira_base}/{args.story_id}.md)"
        if jira_base
        else args.story_id
    )

    lines = [
        f"## Assurance CI Report — {args.story_id}",
        "",
        f"**Ticket**: {ticket_ref}  ",
        f"**Commit**: `{commit_sha}`  **Run**: {timestamp} UTC",
        "",
        "### Gate",
        "",
        f"**{badge}** — {reason}",
        "",
        "### Test Results",
        "",
        "| | Count |",
        "|:---|---:|",
        f"| ✅ Passed | **{passed}** |",
        f"| ❌ Failed | **{failed}** |",
        "",
    ]

    if output.strip():
        lines += [
            "<details>",
            "<summary>Test output</summary>",
            "",
            "```",
            output.strip(),
            "```",
            "",
            "</details>",
            "",
        ]

    lines += [
        "---",
        "_Generated by Assurance CI · "
        "Traceability record committed to `traceability/register.json`_",
    ]

    Path(args.out).write_text("\n".join(lines), encoding="utf-8")
    print(f"PR body written to {args.out}")


if __name__ == "__main__":
    main()
